[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mon2y-trial-daemon"
version = "0.1.0"
dependencies = [
    "requests",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["mon2y_trial_daemon"]

[project.scripts]
mon2y-trial-daemon = "mon2y_trial_daemon.main:main"
