[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mon2y-dist"
version = "0.1.0"
dependencies = [
    "flask",
    "optuna",
    "boto3",
]
package-dir = {"" = "src"}
packages = ["mon2y_dist"]

[project.scripts]
mon2y-dist = "mon2y_dist.main:main"
